package paulbthompson.me.a1960squiz;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.*;

@DynamoDBTable(tableName = "quizs-mobilehub-543059164-highScores")
public class ScoreItem {
    private String scoreId;
    private int score;
    private String firstName;
    private String lastName;

    @DynamoDBHashKey(attributeName = "scoreId")
    @DynamoDBAutoGeneratedKey
    public String getScoreId() {
        return scoreId;
    }

    public void setScoreId(String scoreId) {
        this.scoreId = scoreId;
    }


    @DynamoDBRangeKey(attributeName = "score")
    public int getScore() {
        return score;
    }

    public void setScore(int score) {
        this.score = score;
    }

    @DynamoDBAttribute(attributeName = "firstName")
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @DynamoDBAttribute(attributeName = "lastName")
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


}
