package paulbthompson.me.a1960squiz;

import android.os.Parcel;
import android.os.Parcelable;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.*;

@DynamoDBTable(tableName = "quizs-mobilehub-543059164-highScores")
public class ScoreItem implements Parcelable{
    private String scoreId;
    private int score;
    private String firstName;
    private String lastName;

    @DynamoDBHashKey(attributeName = "scoreId")
    @DynamoDBAutoGeneratedKey
    public String getScoreId() {
        return scoreId;
    }

    public void setScoreId(String scoreId) {
        this.scoreId = scoreId;
    }


    @DynamoDBRangeKey(attributeName = "score")
    public int getScore() {
        return score;
    }

    public void setScore(int score) {
        this.score = score;
    }

    @DynamoDBAttribute(attributeName = "firstName")
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @DynamoDBAttribute(attributeName = "lastName")
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


    /* everything below here is for implementing Parcelable */

    // 99.9% of the time you can just ignore this
    @Override
    public int describeContents() {
        return 0;
    }

    // write your object's data to the passed-in Parcel
    @Override
    public void writeToParcel(Parcel out, int flags) {
        out.writeString(scoreId);
        out.writeInt(score);
        out.writeString(firstName);
        out.writeString(lastName);
    }

    // this is used to regenerate your object. All Parcelables must have a CREATOR that implements these two methods
    public static final Parcelable.Creator<ScoreItem> CREATOR = new Parcelable.Creator<ScoreItem>() {
        public ScoreItem createFromParcel(Parcel in) {
            return new ScoreItem(in);
        }

        public ScoreItem[] newArray(int size) {
            return new ScoreItem[size];
        }
    };

    // example constructor that takes a Parcel and gives you an object populated with it's values
    private ScoreItem(Parcel in) {
        scoreId = in.readString();
        score = in.readInt();
        firstName = in.readString();
        lastName = in.readString();
    }

    public ScoreItem() {

    }

}
